name: server_api
description: A server app using the shelf package and Docker.
version: 1.0.0
homepage: https://eventdrc.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  postgres: ^2.4.3
  dart_jsonwebtoken: ^2.4.1
  yaml: ^3.1.1
  dotenv: ^4.0.1 
  shelf_multipart: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
